### ISSUE TITLE
[enhancement] !value in yaml_parser.py 

### ISSUE THREAD

**Issue by TNick** [lisa-lab/pylearn2#1453]
If I'm not mistaken there is no way right now in a yaml file to extract a value from a previously constructed object. This does not work:
```yaml
!obj:pylearn2.train.Train {
    dataset: &trndataset !pkl: "${DATASET_TRAIN}",
    i_want_shape_here_for_brevity: *trndataset.SHAPE
}
```
By adding a new constructor:
```python
yaml.add_multi_constructor('!value:', multi_constructor_value)
```
that could be accomplished, allowing something like:
```yaml
{
    tesat1: !value: {
        obj_to_call: &bingo !obj:package.module.Bingo {},
        method_to_call: "callMeWithArg",
        arguments: [
            !float "${NETWORK_SCALE}"
        ]
    },
    tesat2: !value: {
        obj_to_call: *bingo,
        method_to_call: "some_value"
    }
}
```
An implementation would then be:
```python
def multi_constructor_value(loader, tag_suffix, node):
    """
    Callback used by PyYAML when a "!value:" tag is encountered.
    """
    if tag_suffix != "" and tag_suffix != u"":
        raise AssertionError('Expected tag_suffix to be "" but it is "'
                             + tag_suffix +
                             '": Put space between !value: and the filename.')

    assert node.tag == '!value:'

    mapping = loader.construct_mapping(node)
    for key in mapping.keys():
        if not isinstance(key, six.string_types):
            message = "Received non string object (%s) as " \
                      "key in mapping." % str(key)
            raise TypeError(message)

    obj_to_call = _instantiate(mapping['obj_to_call'])
    func = getattr(obj_to_call, mapping['method_to_call'])
    if 'arguments' in mapping:
        arguments = mapping['arguments']
    else:
        arguments = None

    if hasattr(func, '__call__'):
        if arguments == None:
            result = func()
        else:
            result = func(arguments)
    else:
        result = func

    return result
```
This should probably make use of `Proxy` but I stand defeated by those. Please improve and let me know if you're interested in a pull request.

**Comment by lamblin** [comment]
I'm not sure we need a new tag and syntax for that, at least to extract attributes.
I think your first example could be rewritten as:

```yaml
!obj:pylearn2.train.Train {
    dataset: &trndataset !pkl: "${DATASET_TRAIN}",
    i_want_shape_here_for_brevity: !obj:__builtin__.getattr {
        object: *trndataset,
        name: SHAPE
    }
}
```
That does not work for methods, though.

Can someone more familiar then me with the YAML syntax comment? @dwf?
